package prob2

import (
	"fmt"

	"github.com/jimmyjames85/goprojecteuler/util"
)

// https://projecteuler.net/problem=2
//
// Each new term in the Fibonacci sequence is generated by adding the previous two terms.
// By starting with 1 and 2, the first 10 terms will be:
//
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//
// By considering the terms in the Fibonacci sequence whose values do not exceed four million,
// find the sum of the even-valued terms.

func Run() {

	ch := make(chan int)
	go util.GenerateFib(ch)

	sum := 0
	for fib := <-ch; fib <= 4000000; fib = <-ch {
		if fib%2 == 0 {
			fmt.Printf("%d\n", fib)
			sum += fib
		}
	}
	fmt.Printf("sum = %d\n", sum)
}
